import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  left,
  right,
}: {
  children: React.ReactNode;
  left: React.ReactNode;
  right: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-cols-3 gap-4">
        {children}
        {left}
        {right}
      </body>
    </html>
  );
}
